name: Hourly check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytz requests

      - name: Run hourly check
        env:
          THINGSPEAK_URL: ${{ secrets.THINGSPEAK_URL }}
        run: python github_actions/hourly_check.py